### ISSUE TITLE
Great little app!

### ISSUE THREAD

**Issue by MatiasNino-REISYS** [zumoshi/BrowserSelect#1]
Thanks for the very handy app! Any chance we can get it to detect the Windows 10 Edge Browser and include it on the list. 

Keep up the great work!

**Comment by zumoshi** [comment]
Hello,
sorry for the delay , i just saw your message , to be honest i didn't really expected anyone to notice this app let alone use it ! i'm happy you found it useful.

try with the last update [v1.0.1](https://github.com/zumoshi/BrowserSelect/releases) it should now list edge as an option.

**Comment by MatiasNino-REISYS** [comment]
Thank you so much! I work in the IT Industry and use multiple browsers for different functions and applications. This app is incredibly handy because it allows me to quickly select a browser to open a link anywhere I click one. Thanks for building it!
