### ISSUE TITLE
IE isn't brought to focus if open already

### ISSUE THREAD

**Issue by JeffGillman** [zumoshi/BrowserSelect#10]
Not sure this is a BrowserSelect issue, it may be a Microsoft issue, but: when IE is open already, and minimized or behind another window, it does not come to the forefront when BrowserSelect hands it a URL. Other browsers tested (Chrome, Firefox) act as expected and come forward. This was shown via desktop shortcuts, Win+R run field, and from Outlook email, on two different Windows 7 computers. Thank you, BrowserSelect is a great program!

**Comment by zumoshi** [comment]
thanks for your report.
i think it might be related to commit [713edf9](https://github.com/zumoshi/BrowserSelect/commit/713edf95d09817ff083d74646a6293bdc5340530). i'll see if i can create a patch to fix it.
i don't personally use IE much so sometimes i fail to notice these things before releasing ...

**Comment by zumoshi** [comment]
please check the last patch to see if the issue is resolved.

**Comment by JeffGillman** [comment]
That has resolved the issue. Thank you!
