### ISSUE TITLE
http: www. prefixes?

### ISSUE THREAD

**Issue by Miles-Ahead** [zumoshi/BrowserSelect#12]
This is perhaps a feature request more than anything.  I do a lot of small utilities that use the clipboard.  I noticed that if I put a web address domain.com or whatnot on the command line of Browser Select I get an error because it does not have the http:// prefix.  Most browsers these days will add that stuff on auto-magically.  So I wonder if there is a way to save some typing by allowing urls like milesaheadsoftware.org?

btw I love the program.  I have browser launcher utilities I wrote myself and it peacefully coexists beautifully.  I hope you keep improving it.  :)

**Comment by zumoshi** [comment]
Hello,
yes, it shouldn't crash on malformed a URL. thanks for your report. I'll try to release a patch soon.

**Comment by zumoshi** [comment]
a new version of BrowserSelect is released. please verify that the issue you mentioned is resolved in this version.

**Comment by Miles-Ahead** [comment]
Thank you.  It works fine.
