### ISSUE TITLE
GUI askew on Windows 7

### ISSUE THREAD

**Issue by BGMcoder** [zumoshi/BrowserSelect#15]
With a fresh install (just minutes now) I opened BrowserSelect.  I think that the GUI is clipped off.
You can see in my screenshot here that my browsers do, indeed appear (except for Maxthon and Greenbrowser, but I don't care so much about those), but there seem to be buttons below the icons that look like they are cut off.

I'm running Windows 7 Pro x64

![screenshot_browserselect_001](https://cloud.githubusercontent.com/assets/1699670/18295531/c4032a7c-7467-11e6-8f69-c5a812925615.png)

**Comment by zumoshi** [comment]
that is weird, I can't reproduce it on my system. give me a few days to get access to a win 7 box to see if I can find out why it's doing that.
do you have any specific themes or programs that modify looks of windows installed on your system?

**Comment by zumoshi** [comment]
![image](https://cloud.githubusercontent.com/assets/4184939/18302229/d1355b14-74eb-11e6-8060-2af1781d0aba.png)
I've just tested v1.3.4 of BrowserSelect on a win7 x64 VM, and it doesn't seem to have any problems.
even though there are not many browsers since it's a clean install, the "Always" button is not out of window boundary.

**Comment by JeffGillman** [comment]
I have also tested on Win7 x64, with the latest version of BrowserSelect, and with three browsers shown (Firefox, Chrome, IE) I do not experience any clipping. I then set my font size to 150%, and still could not reproduce the clipping issue.

**Comment by BGMcoder** [comment]
Hmm, no, I'm not using any special theme, and aero is on.  I am using DisplayFusion, however because I have three monitors.  I also have a Win7 VM - I'll try it on that and see how it goes and report back.  Thanks for the attention.

**Comment by BGMcoder** [comment]
Okay, well, on my VM there was no clipping issue.  Must be something on my workstation.  I uninstalled and reinstalled it on the workstation and it has the same effect.  Strange.

**Comment by zumoshi** [comment]
it's hard to fix it when I can't reproduce it myself, but I'll try to make a patch that makes the window size more generic rather than hard coded in pixels.

**Comment by BGMcoder** [comment]
Thanks; no rush for me however.

**Comment by zumoshi** [comment]
can you try this build ? [BrowserSelect.zip](https://github.com/zumoshi/BrowserSelect/files/459688/BrowserSelect.zip) 
 (or alternatively compile from the source if you have VS set up, but since you said you don't have time i thought i should provide a compiled version)

**Comment by BGMcoder** [comment]
Perfect!  (thanks for the binary)

**Comment by zumoshi** [comment]
so, the "Always" button is not clipped anymore?
could you also verify that other windows also display correctly (e.g. settings, about, help , ...)

**Comment by BGMcoder** [comment]
Well, correct - that's what I meant by "Perfect".  Nothing is clipped.  Settings and About panels are all beautiful, the main window is not clipped at all.  Although, in my opinion, I think the icons are rather large, being around 120px - I would use 64px, myself; but that's just my preference. It looks good!

**Comment by zumoshi** [comment]
thanks, i'll add this patch in the next release.
