### ISSUE TITLE
"Settings" does not work in Windows 7 64 bit and how to set it as the default browser?

### ISSUE THREAD

**Issue by blackicbm** [zumoshi/BrowserSelect#2]
After installing the latest version (1.0.1) in Windows 7 64bit
1. This program is installed in %APPDATA%
2. After launching it, click "Settings" button. It just show the following message
  - I failed to come up with anything to be configured. The program is pretty straightforward, please submit an issue if you think something should be here"
3. May know is there a way to set this as the default browser in this program? or we need to edit the registry key to make it by myself?

**Comment by zumoshi** [comment]
hi,
thanks for reporting the issue . manual modification of registry should not be necessary.
in windows 8/8.1/10 the first time a link is opened after installation a dialogue (as shown in the screenshot in repo readme) will pop up and will let you choose browser select as default browser. i have not tested it in windows 7 though.
i will try to make some tests and release a patch for windows 7.

**Comment by zumoshi** [comment]
try with the v1.0.2 release , I've added an option to make it the default browser in the settings.
