### ISSUE TITLE
Clipped with 125% screen resolution

### ISSUE THREAD

**Issue by joergma** [zumoshi/BrowserSelect#24]
I have Win 7 Pro x64 and Win 10 x64 running, with 125% screen resolution. On both systems the app 
window is clipped - see screenshot [https://pasteboard.co/GFMHvdz.jpg](url)

As BGMcoder mentioned here [https://github.com/zumoshi/BrowserSelect/issues/16](url) I would
also prefer an installation to a "normal" place. Due to enhanced security, my Folder Guard rules are
configured to refuse running programs from Appdata folders. Why not switch to Inno Setup?

**Comment by zumoshi** [comment]
hello,

could you clarify what you mean by `125% screen resolution`? if you mean the scaling, I just tested v1.3.6 on a win10 (build 10240) with scaling set to 125% and did not reproduce the problem.

![2017-08-15 22_36_08-win10 on localhost localdomain](https://user-images.githubusercontent.com/4184939/29329165-2ffd85c8-820a-11e7-9fa3-56686ac45e55.png)

what is the resolution of your system, installed BrowserSelect version, OS build number, any extra apps that can interfere installed?

---

about the setup installing in Program Files, I will accept pull requests. but I don't think that I will redo it myself for now, maybe in a few months.

**Comment by joergma** [comment]
Yes, I mean the scaling - set to 125%
The native and selected screen resolution is 1920x1080 (Laptop display)
Installed BrowserSelect version: 1.3.6
OS Version:  1607
OS Build: 14393.1593
Extra app: [http://windows10_dpi_blurry_fix.xpexplorer.com/](url) - set to "Use Windows 8.1 DPI scaling"

**Comment by zumoshi** [comment]
give me some time to update my win10 vm, and install the app you said to see if I can reproduce the problem.

do you have the app you mentioned installed on your windows 7 too? does the clipping still happen if you disable it?

**Comment by joergma** [comment]
No, the app isn't installed on windows 7
I forgot to mention, that both OSes are running on real metal, not VMs.

On my "old" Asus Laptop:
Windows 7 Pro x64, Version 6.1 (Build 7601: Service Pack 1)
Native & selected screen resolution 1366x768, with 125% scaling.
Theme set to default for screenshot [https://pasteboard.co/GFSzWtA.jpg](url)
No theme patches aboard, sfc /scannow shows nothing wrong.

This old fellow has only about 5 desktop icons, so I switched to **100% scaling**
and -drumroll- **no more clipping** - all buttons visible!

**Comment by zumoshi** [comment]
I have created a patch for browser select to fix your issue, I have tested the new version on win 7 (100% and 125% scale) and on win 10 (version 1703), on 100%, 125%,150% and with dpi fix app that you provided in win8 mode, on 125% without any issues.

but before I release it I would like you to test it to verify that the issue is resolved:
[BrowserSelect-v1.3.7-prerelease.zip](https://github.com/zumoshi/BrowserSelect/files/1228062/BrowserSelect-v1.3.7-prerelease.zip)

**Comment by joergma** [comment]
**Yay!** It works flawlessly on both OSes. Thank you for your patience and the quick fix :+1: 

Regards, Jörg
