### ISSUE TITLE
Chrome not detected

### ISSUE THREAD

**Issue by devilish2o** [zumoshi/BrowserSelect#26]
Hello,

Thanks for your super application, been looking for that for ages.

I'm on Windows 7, Chrome doesn't show up even though it is installed.

Thought browsers would be listed somewhere in user.config but I'm stuck.

Can you help please?

Regards
devilish2o

**Comment by zumoshi** [comment]
Hello,
which version of chrome are you using, also did you use the official installer or a portable version?
it also helps sometimes to set the missing browser as default then switch the default to browser select again.

also, can you post contents of the following registry key?
`SOFTWARE\Clients\StartMenuInternet\Brave\shell\open\command`

use can use [this batch file](https://gist.githubusercontent.com/zumoshi/39c4c04b6d770539964006d10d286ab0/raw/b3e8fbd93b466b3185961106fdae401cf449e61f/registry.bat) to dump it in a text file. (save it with `.bat` extension, then run it, it should create a file named `export.txt` in the same folder)

**Comment by devilish2o** [comment]
Hello,



Just checked still same prb, Chrome is not listed.
Attached is export.txt.
Thanks a lot! Sorry for delay!
--
Ashvin 

    On Wednesday, October 4, 2017, 8:09:37 PM GMT+2, Borhan Hafez <notifications@github.com> wrote:  
 
 
Hello,
which version of chrome are you using, also did you use the official installer or a portable version?
it also helps sometimes to set the missing browser as default then switch the default to browser select again.

also, can you post contents of the following registry key?
SOFTWARE\Clients\StartMenuInternet\Brave\shell\open\command

use can use this batch file to dump it in a text file. (save it with .bat extension, then run it, it should create a file named export.txt in the same folder)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
    
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet]
@="IEXPLORE.EXE"

[HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\FIREFOX.EXE]
@="Mozilla Firefox"

[HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\FIREFOX.EXE\Capabilities]
"ApplicationDescription"="Firefox delivers safe, easy web browsing. A familiar user interface, enhanced security features including protection from online identity theft, and integrated search let you get the most out of the web."
"ApplicationIcon"="C:\\Program Files (x86)\\Mozilla Firefox\\firefox.exe,0"
"ApplicationName"="Firefox"

[HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\FIREFOX.EXE\Capabilities\FileAssociations]
".htm"="FirefoxHTML"
".html"="FirefoxHTML"
".shtml"="FirefoxHTML"
".xht"="FirefoxHTML"
".xhtml"="FirefoxHTML"

[HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\FIREFOX.EXE\Capabilities\StartMenu]
"StartMenuInternet"="FIREFOX.EXE"

[HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\FIREFOX.EXE\Capabilities\URLAssociations]
"ftp"="FirefoxURL"
"http"="FirefoxURL"
"https"="FirefoxURL"

[HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\FIREFOX.EXE\DefaultIcon]
@="C:\\Program Files (x86)\\Mozilla Firefox\\firefox.exe,0"

[HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\FIREFOX.EXE\InstallInfo]
"HideIconsCommand"="\"C:\\Program Files (x86)\\Mozilla Firefox\\uninstall\\helper.exe\" /HideShortcuts"
"ShowIconsCommand"="\"C:\\Program Files (x86)\\Mozilla Firefox\\uninstall\\helper.exe\" /ShowShortcuts"
"ReinstallCommand"="\"C:\\Program Files (x86)\\Mozilla Firefox\\uninstall\\helper.exe\" /SetAsDefaultAppGlobal"
"IconsVisible"=dword:00000001

[HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\FIREFOX.EXE\shell]

[HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\FIREFOX.EXE\shell\open]

[HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\FIREFOX.EXE\shell\open\command]
@="\"C:\\Program Files (x86)\\Mozilla Firefox\\firefox.exe\""

[HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\FIREFOX.EXE\shell\properties]
@="Firefox &Options"

[HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\FIREFOX.EXE\shell\properties\command]
@="\"C:\\Program Files (x86)\\Mozilla Firefox\\firefox.exe\" -preferences"

[HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\FIREFOX.EXE\shell\safemode]
@="Firefox &Safe Mode"

[HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\FIREFOX.EXE\shell\safemode\command]
@="\"C:\\Program Files (x86)\\Mozilla Firefox\\firefox.exe\" -safe-mode"

[HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\IEXPLORE.EXE]
@="Internet Explorer"
"LocalizedString"="@C:\\Program Files\\Internet Explorer\\iexplore.exe,-702"

[HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\IEXPLORE.EXE\DefaultIcon]
@="C:\\Program Files\\Internet Explorer\\iexplore.exe,-9"

[HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\IEXPLORE.EXE\InstallInfo]
"IconsVisible"=dword:00000001
"ShowIconsCommand"="\"C:\\Windows\\System32\\ie4uinit.exe\" -show"
"ReinstallCommand"="\"C:\\Windows\\System32\\ie4uinit.exe\" -reinstall"
"HideIconsCommand"="\"C:\\Windows\\System32\\ie4uinit.exe\" -hide"

[HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\IEXPLORE.EXE\shell]

[HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\IEXPLORE.EXE\shell\naom]
"MUIVerb"="@C:\\Windows\\System32\\ieframe.dll,-39229"

[HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\IEXPLORE.EXE\shell\naom\command]
@="\"C:\\Program Files\\Internet Explorer\\iexplore.exe\" -extoff"

[HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\IEXPLORE.EXE\shell\open]

[HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\IEXPLORE.EXE\shell\open\command]
@="C:\\Program Files\\Internet Explorer\\iexplore.exe"

Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\SOFTWARE\Clients\StartMenuInternet]
@="FIREFOX.EXE"

[HKEY_CURRENT_USER\SOFTWARE\Clients\StartMenuInternet\BROWSERSELECT.EXE]
@="Browser Select"

[HKEY_CURRENT_USER\SOFTWARE\Clients\StartMenuInternet\BROWSERSELECT.EXE\Capabilities]
"ApplicationName"="BrowserSelect"
"ApplicationDescription"="Choose a Browser dynamically."
"ApplicationIcon"="C:\\Users\\fp11606\\AppData\\Local\\BrowserSelect\\BrowserSelect.exe,0"

[HKEY_CURRENT_USER\SOFTWARE\Clients\StartMenuInternet\BROWSERSELECT.EXE\Capabilities\StartMenu]
"StartMenuInternet"="BROWSERSELECT.EXE"

[HKEY_CURRENT_USER\SOFTWARE\Clients\StartMenuInternet\BROWSERSELECT.EXE\Capabilities\URLAssociations]
"http"="bselectURL"
"https"="bselectURL"

[HKEY_CURRENT_USER\SOFTWARE\Clients\StartMenuInternet\BROWSERSELECT.EXE\DefaultIcon]
@="C:\\Users\\fp11606\\AppData\\Local\\BrowserSelect\\BrowserSelect.exe,0"

[HKEY_CURRENT_USER\SOFTWARE\Clients\StartMenuInternet\BROWSERSELECT.EXE\shell]

[HKEY_CURRENT_USER\SOFTWARE\Clients\StartMenuInternet\BROWSERSELECT.EXE\shell\open]

[HKEY_CURRENT_USER\SOFTWARE\Clients\StartMenuInternet\BROWSERSELECT.EXE\shell\open\command]
@="\"C:\\Users\\fp11606\\AppData\\Local\\BrowserSelect\\BrowserSelect.exe\""

**Comment by zumoshi** [comment]
I can see that chrome is missing from the file you provided.
if you look at it there is Firefox and IExplorer, along with their path in it, but no entry for chrome.

note that this registry key is not created by browserSelect, and is the default way for browsers to [advertise themselves to windows](https://msdn.microsoft.com/en-us/library/windows/desktop/dd203067(v=vs.85).aspx). I'm not sure why chrome did not create it, but there is nothing I can do in BrowserSelect to find browsers missing from `startMenuInternet`.

try setting chrome as the default browser to see if it creates them, if not try reinstalling it or alternatively manually [create a record for Chrome](https://gist.github.com/Efreak/f54c12c5297d846001fd#file-original-chrome-handler-reg) there.

**Comment by devilish2o** [comment]
Hello,
Reinstalled offline version as per instructions from here Install Google Chrome in Program Files Folder instead of AppData • Raymond.CC :

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Install Google Chrome in Program Files Folder instead of AppData • Raymo...

If you haven't noticed, Google Chrome by default installs to AppData folder instead of Program Files. However, f...
 |

 |

 |



and everything is fine now !


Thanks again for this wondeful software.
Regards,Ashvin 

    On Wednesday, November 8, 2017, 11:58:27 AM GMT+1, Borhan Hafez <notifications@github.com> wrote:  
 
 
I can see that chrome is missing from the file you provided.
if you look at it there is Firefox and IExplorer, along with their path in it, but no entry for chrome.

note that this registry key is not created by browserSelect, and is the default way for browsers to advertise themselves to windows. I'm not sure why chrome did not create it, but there is nothing I can do in BrowserSelect to find browsers missing from startMenuInternet.

try setting chrome as the default browser to see if it creates them, if not try reinstalling it or alternatively manually create a record for Chrome there.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
    
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet]
@="IEXPLORE.EXE"

[HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\FIREFOX.EXE]
@="Mozilla Firefox"

[HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\FIREFOX.EXE\Capabilities]
"ApplicationDescription"="Firefox delivers safe, easy web browsing. A familiar user interface, enhanced security features including protection from online identity theft, and integrated search let you get the most out of the web."
"ApplicationIcon"="C:\\Program Files (x86)\\Mozilla Firefox\\firefox.exe,0"
"ApplicationName"="Firefox"

[HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\FIREFOX.EXE\Capabilities\FileAssociations]
".htm"="FirefoxHTML"
".html"="FirefoxHTML"
".shtml"="FirefoxHTML"
".xht"="FirefoxHTML"
".xhtml"="FirefoxHTML"

[HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\FIREFOX.EXE\Capabilities\StartMenu]
"StartMenuInternet"="FIREFOX.EXE"

[HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\FIREFOX.EXE\Capabilities\URLAssociations]
"ftp"="FirefoxURL"
"http"="FirefoxURL"
"https"="FirefoxURL"

[HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\FIREFOX.EXE\DefaultIcon]
@="C:\\Program Files (x86)\\Mozilla Firefox\\firefox.exe,0"

[HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\FIREFOX.EXE\InstallInfo]
"HideIconsCommand"="\"C:\\Program Files (x86)\\Mozilla Firefox\\uninstall\\helper.exe\" /HideShortcuts"
"ShowIconsCommand"="\"C:\\Program Files (x86)\\Mozilla Firefox\\uninstall\\helper.exe\" /ShowShortcuts"
"ReinstallCommand"="\"C:\\Program Files (x86)\\Mozilla Firefox\\uninstall\\helper.exe\" /SetAsDefaultAppGlobal"
"IconsVisible"=dword:00000001

[HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\FIREFOX.EXE\shell]

[HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\FIREFOX.EXE\shell\open]

[HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\FIREFOX.EXE\shell\open\command]
@="\"C:\\Program Files (x86)\\Mozilla Firefox\\firefox.exe\""

[HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\FIREFOX.EXE\shell\properties]
@="Firefox &Options"

[HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\FIREFOX.EXE\shell\properties\command]
@="\"C:\\Program Files (x86)\\Mozilla Firefox\\firefox.exe\" -preferences"

[HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\FIREFOX.EXE\shell\safemode]
@="Firefox &Safe Mode"

[HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\FIREFOX.EXE\shell\safemode\command]
@="\"C:\\Program Files (x86)\\Mozilla Firefox\\firefox.exe\" -safe-mode"

[HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\Google Chrome]
@="Google Chrome"

[HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\Google Chrome\Capabilities]
"ApplicationDescription"="Google Chrome est un navigateur Web qui ex‚cute des applications et des pages Web en un temps record. Il est rapide, stable et simple … utiliser. Naviguez sur Internet en toute s‚curit‚ grƒce … la protection int‚gr‚e de Google Chrome contre le phishing et les logiciels malveillants."
"ApplicationIcon"="C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe,0"
"ApplicationName"="Google Chrome"

[HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\Google Chrome\Capabilities\FileAssociations]
".htm"="ChromeHTML"
".html"="ChromeHTML"
".pdf"="ChromeHTML"
".shtml"="ChromeHTML"
".svg"="ChromeHTML"
".xht"="ChromeHTML"
".xhtml"="ChromeHTML"
".webp"="ChromeHTML"

[HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\Google Chrome\Capabilities\Startmenu]
"StartMenuInternet"="Google Chrome"

[HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\Google Chrome\Capabilities\URLAssociations]
"ftp"="ChromeHTML"
"http"="ChromeHTML"
"https"="ChromeHTML"
"irc"="ChromeHTML"
"mailto"="ChromeHTML"
"mms"="ChromeHTML"
"news"="ChromeHTML"
"nntp"="ChromeHTML"
"sms"="ChromeHTML"
"smsto"="ChromeHTML"
"tel"="ChromeHTML"
"urn"="ChromeHTML"
"webcal"="ChromeHTML"

[HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\Google Chrome\DefaultIcon]
@="C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe,0"

[HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\Google Chrome\InstallInfo]
"ReinstallCommand"="\"C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe\" --make-default-browser"
"HideIconsCommand"="\"C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe\" --hide-icons"
"ShowIconsCommand"="\"C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe\" --show-icons"
"IconsVisible"=dword:00000001

[HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\Google Chrome\shell]

[HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\Google Chrome\shell\open]

[HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\Google Chrome\shell\open\command]
@="\"C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe\""

[HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\IEXPLORE.EXE]
@="Internet Explorer"
"LocalizedString"="@C:\\Program Files\\Internet Explorer\\iexplore.exe,-702"

[HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\IEXPLORE.EXE\DefaultIcon]
@="C:\\Program Files\\Internet Explorer\\iexplore.exe,-9"

[HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\IEXPLORE.EXE\InstallInfo]
"IconsVisible"=dword:00000001
"ShowIconsCommand"="\"C:\\Windows\\System32\\ie4uinit.exe\" -show"
"ReinstallCommand"="\"C:\\Windows\\System32\\ie4uinit.exe\" -reinstall"
"HideIconsCommand"="\"C:\\Windows\\System32\\ie4uinit.exe\" -hide"

[HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\IEXPLORE.EXE\shell]

[HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\IEXPLORE.EXE\shell\naom]
"MUIVerb"="@C:\\Windows\\System32\\ieframe.dll,-39229"

[HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\IEXPLORE.EXE\shell\naom\command]
@="\"C:\\Program Files\\Internet Explorer\\iexplore.exe\" -extoff"

[HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\IEXPLORE.EXE\shell\open]

[HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\IEXPLORE.EXE\shell\open\command]
@="C:\\Program Files\\Internet Explorer\\iexplore.exe"

Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\SOFTWARE\Clients\StartMenuInternet]
@="FIREFOX.EXE"

[HKEY_CURRENT_USER\SOFTWARE\Clients\StartMenuInternet\BROWSERSELECT.EXE]
@="Browser Select"

[HKEY_CURRENT_USER\SOFTWARE\Clients\StartMenuInternet\BROWSERSELECT.EXE\Capabilities]
"ApplicationName"="BrowserSelect"
"ApplicationDescription"="Choose a Browser dynamically."
"ApplicationIcon"="C:\\Users\\fp11606\\AppData\\Local\\BrowserSelect\\BrowserSelect.exe,0"

[HKEY_CURRENT_USER\SOFTWARE\Clients\StartMenuInternet\BROWSERSELECT.EXE\Capabilities\StartMenu]
"StartMenuInternet"="BROWSERSELECT.EXE"

[HKEY_CURRENT_USER\SOFTWARE\Clients\StartMenuInternet\BROWSERSELECT.EXE\Capabilities\URLAssociations]
"http"="bselectURL"
"https"="bselectURL"

[HKEY_CURRENT_USER\SOFTWARE\Clients\StartMenuInternet\BROWSERSELECT.EXE\DefaultIcon]
@="C:\\Users\\fp11606\\AppData\\Local\\BrowserSelect\\BrowserSelect.exe,0"

[HKEY_CURRENT_USER\SOFTWARE\Clients\StartMenuInternet\BROWSERSELECT.EXE\shell]

[HKEY_CURRENT_USER\SOFTWARE\Clients\StartMenuInternet\BROWSERSELECT.EXE\shell\open]

[HKEY_CURRENT_USER\SOFTWARE\Clients\StartMenuInternet\BROWSERSELECT.EXE\shell\open\command]
@="\"C:\\Users\\fp11606\\AppData\\Local\\BrowserSelect\\BrowserSelect.exe\""

**Comment by devilish2o** [comment]
Just to add: I think the problem might be because I installed the online version which installs in appdata and doesn't require UAC. That's why there's no entry in registry?
--
Ashvin 

    On Wednesday, November 8, 2017, 12:56:53 PM GMT+1, Ashvin Meetoo <ashvinmeetoo@yahoo.com> wrote:  
 
 Hello,
Reinstalled offline version as per instructions from here Install Google Chrome in Program Files Folder instead of AppData • Raymond.CC :

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Install Google Chrome in Program Files Folder instead of AppData • Raymo...

If you haven't noticed, Google Chrome by default installs to AppData folder instead of Program Files. However, f...
 |

 |

 |



and everything is fine now !


Thanks again for this wondeful software.
Regards,Ashvin 

    On Wednesday, November 8, 2017, 11:58:27 AM GMT+1, Borhan Hafez <notifications@github.com> wrote:  
 
 
I can see that chrome is missing from the file you provided.
if you look at it there is Firefox and IExplorer, along with their path in it, but no entry for chrome.

note that this registry key is not created by browserSelect, and is the default way for browsers to advertise themselves to windows. I'm not sure why chrome did not create it, but there is nothing I can do in BrowserSelect to find browsers missing from startMenuInternet.

try setting chrome as the default browser to see if it creates them, if not try reinstalling it or alternatively manually create a record for Chrome there.

**Comment by zumoshi** [comment]
I doubt it, I have the online version that is installed in AppData, and I have no problem with it, it shows up in BrowserSelect fine.

my best guess would be a conflicting install or incomplete uninstall of a previous version could've messed it up. or maybe if you use apps like CCleaner, they may have deleted its registry keys.

especially since you have it installed in Program files, which is a not the default installation locations a registry cleaner app may think that you do not have chrome installed, therefore consider it's registry keys to be leftovers and delete them.

but it may be for many other reasons. can't say for sure.
