### ISSUE TITLE
Error while generating pattern from url

### ISSUE THREAD

**Issue by kchanlee** [zumoshi/BrowserSelect#27]
First of all, I would thank @zumoshi who built this great handy tool!

Repro steps:
=
(1) Set BrowserSelect as my default browser. 
(2) Click on an URL like http://wwwbaiducom or http://baidu:1234
(3) BrowserSelect pops up
(4) Click "Always" under a browser
(5) Get the error "Error while generating pattern from url"

Workaround
=
Manually add the URL in settings.

**Comment by zumoshi** [comment]
Hello,
thanks for your report.
the auto pattern generator can't create rules for domains that do not have at least one dot (".") in them.
I will fix this in the next release.

**Comment by kchanlee** [comment]
@zumoshi thanks! What's the estimated time of next release? I am looking forward to seeing it.
