### ISSUE TITLE
Protected URL in BrowserSelect is blocked by Outlook 

### ISSUE THREAD

**Issue by kchanlee** [zumoshi/BrowserSelect#28]
Environment
=
* Windows 10 version 1703 x64
* Outlook 2016 x64

Repro steps
=
1. Set BrowserSelect as my default browser
2. Click a link from an email in Outlook
3. BrowserSelect pops up
4. Select a browser (Chrome or Firefox)
5. The selected browser opens the URL, but it is blocked by Office 365:
![snipaste_20171020_110824](https://user-images.githubusercontent.com/2238607/31803596-35f018e6-b587-11e7-933c-03655f9b6400.png)

My opinion
=
Outlook sometimes rewrites/protectes URL in email (e.g. [origin](https://www.baidu.com) -> [rewrited](https://nam06.safelinks.protection.outlook.com/?url=https://www.baidu.com&data=02%7C01%7Csample@sample.com%7C424d6cd5f6584daa1f1d08d517230393%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636440361499939299&sdata=WMGN8Je/40q6r+8JSGuA2lfabEmQzFM+Es1SdywsJng=&reserved=0)) for security reason. When I open the protected URL directly in the browser, it works. But when I open the protected URL in BrowserSelect and then choose a browser, it is blocked. Perhaps it is regarded as malware by outlook server.

**Comment by zumoshi** [comment]
hello,
this seems weird to me that it works if you launch the browser directly but not through browserSelect.
I have to ask, are you logged in into your live/office 365 account in the browser you selected?

also what happens if you right click->copy link and paste in the browser?

**Comment by kchanlee** [comment]
Hi @zumoshi ,

Yes, I have logged in.

If I right click -> copy link an paste in the browser, it works. And I found the difference:
The original link that I copied is URL encoded:
```
https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.sample.com%2FManagementPortal%2FPendingActionsPage&data=02%7C01%7Csample%40sample.com%7C424d6cd5f6584daa1f1d08d517230393%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636440361499939299&sdata=WMGN8Je%2F40q6r+8JSGuA2lfabEmQzFM+Es1SdywsJng%3D&reserved=0
```
But the link after I select browser in BrowserSelect is URL decoded:
```
https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.sample.com%2FManagementPortal%2FPendingActionsPage&data=02%7C01%7Csample%40sample.com%7C424d6cd5f6584daa1f1d08d517230393%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636440361499939299&sdata=WMGN8Je%2F40q6r+8JSGuA2lfabEmQzFM+Es1SdywsJng%3D&reserved=0
```

So I think it is probably the URL decoding in BrowserSelect that causes the issue.

**Comment by zumoshi** [comment]
nice find.
please try with v1.3.8, I've fixed the unescaping of URL

**Comment by JeffGillman** [comment]
Nice job! Works as advertised with SafeLinks-encased URLs.

**Comment by kchanlee** [comment]
@zumoshi I've tried v1.3.8 and the issue is resolved. Thanks for the timely fix!
