### ISSUE TITLE
List chrome profiles as separate options

### ISSUE THREAD

**Issue by zumoshi** [zumoshi/BrowserSelect#29]
originally requested through email.

to launch:
```
chrome --profile-directory={profile} {url}
```
to discover: (until i find a better way)
```
glob %localappdata%\google\chrome\*\Google Profile.ico
```
folder name is profile name, and the `.ico` file is the icon

**Comment by miguel-ka** [comment]
Yes that would be perfect. I am using chrome profiles extensively, as I have multiple Logins with Microsoft ID, Azure AD, Google (each private and Business and customer/demo accounts). Logins get confused once you are using the same browser.

Also for software testers it is good to have different Chrome profiles with different Security Setting/roles.

**Comment by tdalon** [comment]
+1 for this request

**Comment by miguel-ka** [comment]
@zumoshi Thank you! Great improvement!
Just a little thing: When I deselct one of multiple Chrome profiles in BrowserSelect settings, Chrome is completely remove. Either all or none, but confusing because the checkbox stays selected for some of them.

**Comment by zumoshi** [comment]
@miguel-ka this feature was coded by @kueswol, not me.
I've already mentioned this bug to him on #39 

it will be fixed in the next release when I had the time or if he fixes it.

**Comment by kueswol** [comment]
@miguel-ka sorry, didn't think through effects of the change on this feature. I'll have a look to properly bring the deselection back without the need for everyone to manually update the settings file.

As a workaround, if you don't actually use the Chrome profiles you may simply rename the file "%localappdata%\Google\Chrome\User Data\_<ProfileName>_\Google Profile.ico" to something else for BrowserSelect not to discover it.
