### ISSUE TITLE
error in windows 10 .htm file reverted to edge

### ISSUE THREAD

**Issue by c-h-u-c-k** [zumoshi/BrowserSelect#3]
In windows 10, it appears something is slightly messed up with .htm file handling, or so win10 thinks.

**Comment by zumoshi** [comment]
hello,
this program does not handle .html and .htm files. you can simply right click and use the open with menu to choose desired browser.
this program is intended for application with clickable url's in them , e.g. pdf reader , notepad++ , messenger application ,... where the only way to open in another browser is to copy the url than open desired browser manually and paste in the address bar.

-Bor

**Comment by zumoshi** [comment]
hello,
this program does not handle .html and .htm files. you can simply right click and use the open with menu to choose desired browser.
this program is intended for application with clickable url's in them , e.g. pdf reader , notepad++ , messenger application ,... where the only way to open in another browser is to copy the url than open desired browser manually and paste in the address bar.

-Bor

**Comment by zumoshi** [comment]
hello,
this program does not handle .html and .htm files. you can simply right click and use the open with menu to choose desired browser.
this program is intended for application with clickable url's in them , e.g. pdf reader , notepad++ , messenger application ,... where the only way to open in another browser is to copy the url than open desired browser manually and paste in the address bar.

-Bor

**Comment by zumoshi** [comment]
hello,
this program does not handle .html and .htm files. you can simply right click and use the open with menu to choose desired browser.
this program is intended for application with clickable url's in them , e.g. pdf reader , notepad++ , messenger application ,... where the only way to open in another browser is to copy the url than open desired browser manually and paste in the address bar.

-Bor

**Comment by c-h-u-c-k** [comment]
I'm not sure why windows was complaining about .htm or .html files. I never set it as the default app for any file types. It gave me an error in a popup but browser select is still working great. And thanks for making and supporting this!
