### ISSUE TITLE
Remove browser from BrowserSelect window

### ISSUE THREAD

**Issue by zeepster** [zumoshi/BrowserSelect#4]
Hello Dev,

I'm sorry for using your email before. :)

My issue is that i would like to remove a browser from the popup window. 
IE is visible as a choice but i never use it.

I hope you can take this into consideration.
Thanks again for this app!

**Comment by zumoshi** [comment]
Hi,
please download the last version and see if it works as desired.

**Comment by zeepster** [comment]
Hi, It does! Thanks.
In the new version i can unselect IE.
