### ISSUE TITLE
Do not close the program after redirect link to the browser

### ISSUE THREAD

**Issue by borgius** [zumoshi/BrowserSelect#40]
It's take time to start BrowserSelect for each link. Can you just move app to tray after you click the button?

**Comment by zumoshi** [comment]
I prefer to optimize the app so it wouldn't take time for it to start, as opposed to having the app be running 24/7 consuming system resources when not needed.

is it really that slow? how long does it take for it to start up?
also how many browsers do you have? and if you don't mind can you check if v1.4 is slower than v1.3.9 or not?

currently, browserSelect looks for browsers/chrome profiles on your system and performs validity checks and extracts their icons on every launch, there is room for improvement by caching the list/icons.

**Comment by borgius** [comment]
I have 4 chrome profiles, Firefox, IE, Edge. it takes around 3 sec to start.

You can add this functionality as an option, if somebody doesn't like it has run, he can disable it.

For my opinion time between link click and browser choice - its most important characteristic.

Thank you!

**Comment by zumoshi** [comment]
I'm going to close this issue since startup speed has been increased in v1.4.1.
Please feel free to reopen it if you still think keeping the app open in the background can be beneficial or if you are still experiencing a slow (>1s) startup time.
