### ISSUE TITLE
Cannot make BrowserSelect kick in on Windows 10

### ISSUE THREAD

**Issue by kikr-as3** [zumoshi/BrowserSelect#44]
Hi... Would love to try BrowserSelect, but cannot make it work.

Tried 1.3.9 and 1.4.0. It installs and I can go to settings. However, I cannot make it use other browser (Edge) on certain URLs, like *.visualstudio.com/* NOR can I make it display browserselect when clicking links in Outlook, Acrobat or browsers.

Im I missing something basic or are there problems on Windows 10 (1709 and 1803)?
Noticed it installs under my profile /appdate/local - is that OK?

Thanks!

/Kim

**Comment by kikr-as3** [comment]
Dooh - missed to select it as Default Browser - sorry about that!
Seems to work as intended now - great :-)

/Kim

**Comment by zumoshi** [comment]
hi,
I know you've already closed this issue but I was halfway typing this so I might as well send it for other users.

I don't personally use Windows 10, so I haven't really tested BrowserSelect throughly on it, it seems that pressing "set as default browser" button on settings causes win10 to reset the browser to edge:
![image](https://user-images.githubusercontent.com/4184939/43309867-3c610686-919b-11e8-958a-7558a275ad46.png)
however, browserSelect itself works fine after you set it as the default browser, there are two ways to do that, which I've just tested on win 10 version 1703 build 15063.413

1. the first time you open an URL after you install it you should get this prompt:
![image](https://user-images.githubusercontent.com/4184939/43309933-6b7a4450-919b-11e8-8f15-5739147eaec6.png)
clicking on browser select then ok sets it as default.

2. if you've missed that you can go to control panel and search default programs then set associations and choose HTTP, click on change program, and you get the same prompt.
![image](https://user-images.githubusercontent.com/4184939/43310033-b1c65548-919b-11e8-81a8-0095a73f4011.png)

**Comment by kikr-as3** [comment]
Thanks Borhan.

An even easier third way in Windows 10:

Start - Type “Default” – Choose “Default app settings”
Scroll down to “Web browser” and select BrowserSelect in the list.


[cid:image001.png@01D42595.C6358CA0]


/Kim
