### ISSUE TITLE
Should be able to hide some profiles from Google Chrome, but not others.

### ISSUE THREAD

**Issue by kasajian** [zumoshi/BrowserSelect#52]
I have about a dozen Google Chrome profiles, some of which I rarely use.   It makes the browser selection dialog very long, and it doesn't fit the horizontal screen at times, without scrolling around.

I can disable certain browsers from this app, but I cannot do the same with certain chrome profiles.   If I disable Chrome altogether, and none of the profiles show up.

**Comment by zumoshi** [comment]
Hi,
Thanks for your report and sorry for the delay.

Please feel free to reopen this issue if you are still experiencing the problem in v1.4.1
