### ISSUE TITLE
Make filter changes more likely to be saved

### ISSUE THREAD

**Issue by JeffGillman** [zumoshi/BrowserSelect#7]
First of all, thanks for this program, it's better than similar programs. I would like to introduce a group of people to BrowserSelect, but I'm worried that the method by which filters are added will confuse them (they are not power users). I think that "make sure to fill all the fields (pattern and browser) and select another row before closing to make sure it will be saved successfully" might be better served by implementing a Save button. (I also understand the dangers of feature creep, and see the value in teaching users how some things work by making them use them as they are.)

**Comment by zumoshi** [comment]
hi,
I see your point, I was mostly inspired by how navicat and similar database management programs work, that your changes are saved when the row you were editing lost focus.
I'll try to add a save button to that dialogue soon.
