### ISSUE TITLE
Linux version?

### ISSUE THREAD

**Issue by seffyroff** [zumoshi/BrowserSelect#74]
I find myself using a Linux desktop more frequently than Windows these days, and I sorely miss BrowserSelect <3

I realise that .net/mono doesn't mean automatic Linux compatibility, and the work would be likely significant, but it would be really cool.

As far as I can tell, there's no other existing mechanism for this on Linux desktop.  I would be happy to be proved wrong there though.

I imagine running it via Wine would be a nope.

**Comment by zumoshi** [comment]
The main issue is not running it, but the browser discovery mechanism which atm is relying on browsers creating keys in StartUpInternet section of the registry which doesn't exist in Linux.
Depending on which DE you use browsers have different ways of announcing their presence, In gnome, for example, we would need to use [`xdg-mime query`](https://askubuntu.com/a/467920/230342).
It's not a matter of it not being possible just that someone has to add the logic for it to work, I will accept pull requests if you do it but I don't have the time to do it myself atm.

As for running it in wine, it will probably work, except that it would only detect browsers installed inside wine not native ones.

As for alternatives I found this one:
https://braus.properlypurple.com/
Haven't used it though so no comment on quality.

**Comment by seffyroff** [comment]
Random reply: I use your software every day and it truly enriches my experience.  Thanks so much.  I would like to show $upport somehow?
